version: '3.8'

volumes:
  database-vol:

networks:
  web-app:

services:
  api:
    build: .
    container_name: api
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - web-app
    environment:
      - DATABASE_URL=postgresql://admin:123456@db:5432/database?schema=public

  db:
    image: postgres
    container_name: db
    restart: unless-stopped
    networks:
      - web-app
    ports:
      - 5432:5432
    volumes:
      - database-vol:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=database